apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backup-system-pvc-restic
  labels:
    app.kubernetes.io/name: backup-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: backup-system-pvc-restic
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
  data:
    - secretKey: RESTIC_PASSWORD
      remoteRef:
        key: backup/pvc-restic
        property: RESTIC_PASSWORD
