apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backup-recovery-forgejo-repo
  labels:
    app.kubernetes.io/name: backup-system
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: backup-recovery-forgejo-repo
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
  data:
    - secretKey: username
      remoteRef:
        key: forgejo/argocd-repo
        property: username
    - secretKey: password
      remoteRef:
        key: forgejo/argocd-repo
        property: password
