apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backup-system-s3-mirror-crypt
  labels:
    app.kubernetes.io/name: backup-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: backup-system-s3-mirror-crypt
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
  data:
    - secretKey: RCLONE_CRYPT_PASSWORD
      remoteRef:
        key: backup/s3-mirror-crypt
        property: RCLONE_CRYPT_PASSWORD
    - secretKey: RCLONE_CRYPT_PASSWORD2
      remoteRef:
        key: backup/s3-mirror-crypt
        property: RCLONE_CRYPT_PASSWORD2
