apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-target
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  labels:
    darksite.cloud/backup: skip
    darksite.cloud/backup-skip-reason: backup-artifacts
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: ""
