apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: valkey-auth
  labels:
    app.kubernetes.io/name: forgejo-valkey
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: valkey-auth
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: password
      remoteRef:
        key: forgejo/redis
        property: password
