apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forgejo
namePrefix: forgejo-
resources:
  - ../../../data/valkey/base
  - externalsecret.yaml
patches:
  - path: patch-statefulset-storage.yaml
    target:
      kind: StatefulSet
      name: valkey
  - path: patch-env.yaml
  - path: patch-vpa-requests-statefulset-forgejo-valkey.yaml
  - path: patch-vpa-requests-statefulset-forgejo-valkey-sentinel.yaml
