apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - externalsecret.yaml
  - certificate.yaml
  - service.yaml
  - deployment.yaml
  - networkpolicy.yaml
  - networkpolicy-smoke-egress.yaml
  - ciliumnetworkpolicy-smoke-kube-apiserver.yaml
  - rbac.yaml
  - cronjob-smoke.yaml

configMapGenerator:
  - name: keycloak-upstream-sim-scripts
    files:
      - scripts/bootstrap.sh
      - scripts/smoke.sh

generatorOptions:
  disableNameSuffixHash: true
