apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: keycloak-upstream-sim-ingress
  namespace: keycloak-upstream-sim
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: keycloak-upstream-sim
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: keycloak
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 8443
