apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak-operator
resources:
  - namespace.yaml
  - crds/keycloaks.k8s.keycloak.org-v1.yaml
  - crds/keycloakrealmimports.k8s.keycloak.org-v1.yaml
  - crds/servicemonitors.monitoring.coreos.com-v1.yaml
  - operator-bundle.yaml
patches:
  - path: patch-vpa-requests-deployment-keycloak-operator.yaml
  - path: patch-ha-tier-labels.yaml
