apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config.yaml
  - backup.yaml
  - tenant-backup-provisioner-role.yaml
  - tenant-s3-provisioner-role.yaml
  - tenant-smoke-backup-secret-sync.yaml
  - tenant-smoke-backup-crypto-delete.yaml
  - jwt-config.yaml
  - oidc-config.yaml
  - platform-rbac.yaml
  - tenant-rbac.yaml
  - tenant-eso.yaml
  - tenant-dns-rfc2136.yaml
  - destinationrule-kube-apiserver.yaml
  - destinationrule-kms-shim-istio-mtls.yaml
  - secret-vault-kubernetes-tokenreviewer.yaml
  - tokenreview-binding.yaml
  - ../../../shared/bootstrap-scripts/istio-native-exit
  - tests

configMapGenerator:
  - name: vault-configure-script
    namespace: vault-system
    files:
      - scripts/configure.sh
  - name: vault-jwt-config-script
    namespace: vault-system
    files:
      - scripts/jwt-config.sh
  - name: vault-oidc-config-script
    namespace: vault-system
    files:
      - scripts/oidc-config.sh
  - name: vault-tenant-rbac-config-script
    namespace: vault-system
    files:
      - scripts/tenant-rbac.sh
  - name: vault-platform-rbac-config-script
    namespace: vault-system
    files:
      - scripts/platform-rbac.sh
  - name: vault-tenant-eso-config-script
    namespace: vault-system
    files:
      - scripts/tenant-eso.sh
  - name: vault-tenant-dns-rfc2136-config-script
    namespace: vault-system
    files:
      - scripts/tenant-dns-rfc2136.sh
  - name: vault-tenant-backup-provisioner-role-script
    namespace: vault-system
    files:
      - scripts/tenant-backup-provisioner-role.sh
  - name: vault-tenant-s3-provisioner-role-script
    namespace: vault-system
    files:
      - scripts/tenant-s3-provisioner-role.sh
  - name: vault-tenant-smoke-backup-secret-sync-script
    namespace: vault-system
    files:
      - scripts/tenant-smoke-backup-secret-sync.sh
  - name: vault-tenant-smoke-backup-crypto-delete-script
    namespace: vault-system
    files:
      - scripts/tenant-smoke-backup-crypto-delete.sh

generatorOptions:
  disableNameSuffixHash: true
