apiVersion: v1
kind: Secret
metadata:
  name: vault-kubernetes-tokenreviewer
  namespace: vault-system
  annotations:
    kubernetes.io/service-account.name: vault
type: kubernetes.io/service-account-token
