apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mimir
commonAnnotations:
  argocd.argoproj.io/sync-wave: "2.5"

resources:
  - ../../../../shared/bootstrap-scripts/istio-native-exit
  - rules/
  - peerauthentication-mimir.yaml
  - destinationrules-mimir-istio-mutual.yaml
  - vpa-common.yaml
