apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: keycloak
  labels:
    app.kubernetes.io/name: keycloak
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
