apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: harbor
resources:
  - serviceaccount-oidc-config.yaml
  - rbac-oidc-config.yaml
  - job-harbor-oidc-config.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - job-harbor-smoke.yaml
