apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forgejo
resources:
  - ../../base
  - ../../tests
patches:
  - target:
      kind: Job
      name: forgejo-smoke
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: forgejo.dev-single.internal.example.com
  - path: patch-oidc-config-url-mac-orbstack-single.yaml
    target:
      kind: Job
      name: forgejo-oidc-config
