apiVersion: v1
kind: Namespace
metadata:
  name: t-<orgId>-p-<projectId>-prod-app
  labels:
    darksite.cloud/rbac-profile: tenant
    darksite.cloud/tenant-id: <orgId>
    darksite.cloud/project-id: <projectId>
    observability.grafana.com/tenant: <orgId>
