apiVersion: batch/v1
kind: Job
metadata:
  name: forgejo-oidc-config
  namespace: forgejo
spec:
  template:
    spec:
      containers:
        - name: configure
          env:
            - name: OIDC_DISCOVERY_URL
              value: https://keycloak.prod.internal.example.com/realms/deploykube-admin/.well-known/openid-configuration
