apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: tempo-api-from-gateway
  namespace: tempo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tempo
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/istio-system/sa/public-gateway-istio

