apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - httproute-loki.yaml
  - httproute-tempo.yaml
  - httproute-mimir.yaml
  - authorizationpolicy-loki-api.yaml
  - authorizationpolicy-tempo-api.yaml
  - authorizationpolicy-mimir-api.yaml

