apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - ../../base
patches:
  - path: patch-vpa-requests-deployment-argocd-ui-extensions.yaml
  - path: patch-ha-tier-labels.yaml
