apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-admin-password
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: harbor-admin-password
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: HARBOR_ADMIN_PASSWORD
      remoteRef:
        key: harbor/admin
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-core-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: harbor-core-secret
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: secret
      remoteRef:
        key: harbor/core
        property: secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-core-xsrf
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: harbor-core-xsrf
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: CSRF_KEY
      remoteRef:
        key: harbor/core
        property: csrfKey
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-secret-key
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: harbor-secret-key
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: secretKey
      remoteRef:
        key: harbor/core
        property: secretKey
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-jobservice
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: harbor-jobservice
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: JOBSERVICE_SECRET
      remoteRef:
        key: harbor/jobservice
        property: secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-registry
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: harbor-registry
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: REGISTRY_HTTP_SECRET
      remoteRef:
        key: harbor/registry
        property: httpSecret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-registry-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: harbor-registry-credentials
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: REGISTRY_PASSWD
      remoteRef:
        key: harbor/registry
        property: credentialsPassword
    - secretKey: REGISTRY_HTPASSWD
      remoteRef:
        key: harbor/registry
        property: credentialsHtpasswd
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-db
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: harbor-db
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: password
      remoteRef:
        key: harbor/database
        property: appPassword
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-oidc-client
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: harbor-oidc-client
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
    - extract:
        key: keycloak/harbor-client
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-oidc-ca
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: harbor-oidc-ca
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: ca.crt
      remoteRef:
        key: keycloak/oidc-ca
        property: ca_crt
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: harbor-selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-token-cert
spec:
  secretName: harbor-token-cert
  commonName: harbor-token-service
  duration: 87600h # 10y
  renewBefore: 720h # 30d
  issuerRef:
    name: harbor-selfsigned
    kind: Issuer
