apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: k8s-oidc-runtime-smoke-client
  namespace: access-guardrails-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: k8s-oidc-runtime-smoke-client
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
    - extract:
        key: keycloak/k8s-oidc-runtime-smoke-client
