apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

configMapGenerator:
  - name: step-ca-vault-seed-script
    files:
      - scripts/seed.sh

generatorOptions:
  disableNameSuffixHash: true

resources:
  - ../../../shared/bootstrap-scripts/istio-native-exit
  - rbac.yaml
  - job.yaml
