apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault-seal-system
resources:
  - namespace.yaml
  - service.yaml
  - deployment.yaml
  - pdb.yaml
  - networkpolicy.yaml
  - tests
configMapGenerator:
  - name: kms-shim-script
    files:
      - kms_shim.py
patches:
  - path: patch-vpa-requests-deployment-kms-shim.yaml
  - path: patch-ha-tier-labels.yaml
