apiVersion: v1
kind: Namespace
metadata:
  name: vault-seal-system
  labels:
    app.kubernetes.io/part-of: secrets-stack
    deploykube.gitops/component: kms-shim
    deploykube.gitops/owner: secrets
    istio-injection: enabled
    observability.grafana.com/tenant: platform

