apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kms-shim
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: kms-shim
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - podSelector: {}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: vault-system
      ports:
        - protocol: TCP
          port: 8200
  egress: []

