apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-postgres-superuser
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: forgejo-postgres-superuser
    creationPolicy: Owner
    template:
      mergePolicy: Merge
      type: Opaque
      data:
        username: postgres
  data:
    - secretKey: password
      remoteRef:
        key: forgejo/database
        property: superuserPassword
