apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-app.yaml
  # Optional: support sessions (platform-owned; time-bound)
  # - ../../../../support-sessions/<sessionId>
  - externalsecret-factorio.yaml
  - externalsecret-factorio-backup.yaml
