apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tenant-s3-app
  namespace: t-other-p-demo-prod-app
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: tenant-s3-app
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata: {}
      type: Opaque
  data:
    - secretKey: S3_ENDPOINT
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: tenants/other/s3/app
        metadataPolicy: None
        property: S3_ENDPOINT
    - secretKey: S3_REGION
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: tenants/other/s3/app
        metadataPolicy: None
        property: S3_REGION
    - secretKey: BUCKET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: tenants/other/s3/app
        metadataPolicy: None
        property: S3_BUCKET
    - secretKey: S3_ACCESS_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: tenants/other/s3/app
        metadataPolicy: None
        property: S3_ACCESS_KEY
    - secretKey: S3_SECRET_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: tenants/other/s3/app
        metadataPolicy: None
        property: S3_SECRET_KEY
