apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-postgres-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: harbor-postgres-app
    creationPolicy: Owner
    template:
      mergePolicy: Merge
      type: Opaque
      data:
        database: registry
        username: harbor
  data:
    - secretKey: password
      remoteRef:
        key: harbor/database
        property: appPassword

