apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - platform.darksite.cloud_platformapps.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - deployment.yaml
  - platformapps.platform.darksite.cloud.yaml
