apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rbac-namespace-sync
subjects:
  - kind: ServiceAccount
    name: rbac-namespace-sync
    namespace: rbac-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rbac-namespace-sync
