apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - operator-namespace.yaml
  - crds.yaml
  - istio-operator-crd.yaml
  - operator-rendered.yaml
  - istio-operator.yaml
  - tests
patches:
  - path: patch-vpa-requests-deployment-istio-operator.yaml

