apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-postgres-keycloak
  namespace: argocd
spec:
  source:
    path: components/data/postgres/overlays/mac-orbstack-single/keycloak
