apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-external-secrets
  namespace: argocd
spec:
  source:
    path: components/secrets/external-secrets/overlays/mac-orbstack-single
