apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-oidc-client
  namespace: forgejo
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: forgejo-oidc-client
    creationPolicy: Owner
  data:
    - secretKey: key
      remoteRef:
        key: keycloak/forgejo-client
        property: clientId
    - secretKey: secret
      remoteRef:
        key: keycloak/forgejo-client
        property: clientSecret
