apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-upstream-scim
  namespace: keycloak
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: keycloak-upstream-scim
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
    - extract:
        key: keycloak/upstream-scim
