apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-vault-automation-user
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: keycloak-vault-automation-user
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: keycloak/vault-automation-user
        property: username
    - secretKey: password
      remoteRef:
        key: keycloak/vault-automation-user
        property: password
