apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kiali-oidc-client
  namespace: istio-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: kiali
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app: kiali
  data:
    - secretKey: oidc-secret
      remoteRef:
        key: keycloak/kiali-client
        property: clientSecret
