apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-postgres-superuser
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: keycloak-postgres-superuser
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        username: postgres
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: keycloak/database
        property: password
