apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-argocd-client
  namespace: keycloak
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: keycloak-argocd-client
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
    - extract:
        key: keycloak/argocd-client
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-forgejo-client
  namespace: keycloak
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: keycloak-forgejo-client
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
    - extract:
        key: keycloak/forgejo-client
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-kiali-client
  namespace: keycloak
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: keycloak-kiali-client
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
    - extract:
        key: keycloak/kiali-client
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-harbor-client
  namespace: keycloak
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: keycloak-harbor-client
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
    - extract:
        key: keycloak/harbor-client
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-hubble-client
  namespace: keycloak
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: keycloak-hubble-client
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
    - extract:
        key: keycloak/hubble-client
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-vault-client
  namespace: keycloak
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: keycloak-vault-client
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
    - extract:
        key: keycloak/vault-client
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-grafana-client
  namespace: keycloak
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: keycloak-grafana-client
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: clientSecret
      remoteRef:
        key: observability/grafana/oidc
        property: clientSecret
