apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-database
  namespace: keycloak
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: keycloak-db
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        POSTGRES_DB: "{{ .database }}"
        POSTGRES_USER: "{{ .username }}"
        POSTGRES_PASSWORD: "{{ .password }}"
        database: "{{ .database }}"
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: database
      remoteRef:
        key: keycloak/database
        property: database
    - secretKey: username
      remoteRef:
        key: keycloak/database
        property: username
    - secretKey: password
      remoteRef:
        key: keycloak/database
        property: password
