apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-dev-user
  namespace: keycloak
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: keycloak-dev-user
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: username
      remoteRef:
        key: keycloak/dev-user
        property: username
    - secretKey: password
      remoteRef:
        key: keycloak/dev-user
        property: password
