apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - externalsecret-admin.yaml
  - externalsecret-dev-user.yaml
  - externalsecret-database.yaml
  - externalsecret-database-superuser.yaml
  - externalsecret-argocd.yaml
  - externalsecret-forgejo.yaml
  - externalsecret-oidc-clients.yaml
  - externalsecret-argocd-automation-user.yaml
  - externalsecret-vault-automation-user.yaml
  - externalsecret-automation-user.yaml
  - externalsecret-kiali.yaml
  - externalsecret-upstream-oidc.yaml
  - externalsecret-upstream-saml.yaml
  - externalsecret-upstream-ldap.yaml
  - externalsecret-upstream-scim.yaml
