apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minecraft-monifactory-backup
  namespace: minecraft-monifactory
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-core
    kind: ClusterSecretStore
  target:
    name: minecraft-monifactory-backup
    creationPolicy: Owner
  data:
    - secretKey: S3_ACCESS_KEY
      remoteRef:
        key: apps/minecraft-monifactory/backup
        property: S3_ACCESS_KEY
    - secretKey: S3_SECRET_KEY
      remoteRef:
        key: apps/minecraft-monifactory/backup
        property: S3_SECRET_KEY
    - secretKey: S3_REGION
      remoteRef:
        key: apps/minecraft-monifactory/backup
        property: S3_REGION
    - secretKey: S3_ENDPOINT
      remoteRef:
        key: apps/minecraft-monifactory/backup
        property: S3_ENDPOINT
    - secretKey: S3_BUCKET
      remoteRef:
        key: apps/minecraft-monifactory/backup
        property: S3_BUCKET
    - secretKey: RESTIC_REPOSITORY
      remoteRef:
        key: apps/minecraft-monifactory/backup
        property: RESTIC_REPOSITORY
    - secretKey: RESTIC_PASSWORD
      remoteRef:
        key: apps/minecraft-monifactory/backup
        property: RESTIC_PASSWORD
