apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minecraft-monifactory-secrets
  namespace: minecraft-monifactory
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-core
    kind: ClusterSecretStore
  target:
    name: minecraft-monifactory-secrets
    creationPolicy: Owner
  data:
    - secretKey: curseforgeApiKey
      remoteRef:
        key: apps/minecraft-monifactory
        property: curseforgeApiKey
    - secretKey: rconPassword
      remoteRef:
        key: apps/minecraft-monifactory
        property: rconPassword
