apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minecraft-monifactory-access
  namespace: minecraft-monifactory
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-core
    kind: ClusterSecretStore
  target:
    name: minecraft-monifactory-access
    creationPolicy: Owner
  data:
    - secretKey: whitelist
      remoteRef:
        key: apps/minecraft-monifactory/access
        property: whitelist
    - secretKey: ops
      remoteRef:
        key: apps/minecraft-monifactory/access
        property: ops
