apiVersion: v1
kind: Namespace
metadata:
  name: minecraft-monifactory
  labels:
    app.kubernetes.io/name: minecraft-monifactory
    app.kubernetes.io/component: game-server
    darksite.cloud/restore-validation-scope: enabled
