apiVersion: v1
kind: Service
metadata:
  name: minecraft-rcon
  namespace: minecraft-monifactory
spec:
  type: ClusterIP
  ports:
    - name: rcon
      port: 25575
      protocol: TCP
      targetPort: rcon
  selector:
    app: minecraft-monifactory

