apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: grafana-admin
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        admin-user: "{{ .username }}"
        admin-password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: observability/grafana
        property: username
    - secretKey: password
      remoteRef:
        key: observability/grafana
        property: password
