apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oidc
  namespace: grafana
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: grafana-oidc
    creationPolicy: Owner
  data:
    - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
      remoteRef:
        key: observability/grafana/oidc
        property: clientId
    - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
      remoteRef:
        key: observability/grafana/oidc
        property: clientSecret
    - secretKey: GF_AUTH_GENERIC_OAUTH_AUTH_URL
      remoteRef:
        key: observability/grafana/oidc
        property: authUrl
    - secretKey: GF_AUTH_GENERIC_OAUTH_TOKEN_URL
      remoteRef:
        key: observability/grafana/oidc
        property: tokenUrl
    - secretKey: GF_AUTH_GENERIC_OAUTH_API_URL
      remoteRef:
        key: observability/grafana/oidc
        property: apiUrl
