apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mimir-alertmanager-notifications
  namespace: mimir
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: mimir-alertmanager-notifications
    creationPolicy: Owner
  data:
    - secretKey: ALERTMANAGER_PLATFORM_WEBHOOK_URL
      remoteRef:
        key: observability/alertmanager
        property: platformWebhookUrl
    - secretKey: ALERTMANAGER_BACKUP_WEBHOOK_URL
      remoteRef:
        key: observability/alertmanager
        property: backupWebhookUrl
