apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-s3
  namespace: loki
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: loki-s3
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: garage/s3
        property: S3_ACCESS_KEY
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: garage/s3
        property: S3_SECRET_KEY
    - secretKey: S3_BUCKET
      remoteRef:
        key: garage/s3
        property: BUCKET_LOGS
    - secretKey: S3_ENDPOINT
      remoteRef:
        key: garage/s3
        property: S3_ENDPOINT
    - secretKey: S3_REGION
      remoteRef:
        key: garage/s3
        property: S3_REGION
