apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-wave: "1"
resources:
  - externalsecret-loki-s3.yaml
  - externalsecret-tempo-s3.yaml
  - externalsecret-mimir-s3.yaml
  - externalsecret-mimir-alertmanager-notifications.yaml
  - externalsecret-grafana-admin.yaml
  - externalsecret-grafana-oidc.yaml

configMapGenerator:
  - name: observability-root-ca
    files:
      - ca.crt=ca.crt
    options:
      disableNameSuffixHash: true
      labels:
        deploykube.gitops/component: observability
        deploykube.gitops/owner: platform
generatorOptions:
  disableNameSuffixHash: true
