apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: powerdns-api
  namespace: dns-system
  labels:
    app: powerdns
    component: api
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: powerdns-api
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: api_key
      remoteRef:
        key: dns/powerdns/api
        property: apiKey
