apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform-ops
resources:
  - cronjob.yaml
  - rbac.yaml
  - smoke-tests/
configMapGenerator:
  - name: istio-cert-monitor-scripts
    files:
      - run.sh
      - monitor.py
  - name: istio-cert-monitor-config
    files:
      - targets.json
generatorOptions:
  disableNameSuffixHash: true
