apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: garage-s3
  namespace: garage
spec:
  host: garage.garage.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    portLevelSettings:
      - port:
          number: 3901
        tls:
          mode: DISABLE
