apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-credentials
  labels:
    app.kubernetes.io/name: garage
    app.kubernetes.io/component: object-storage
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: garage-credentials
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: GARAGE_ADMIN_TOKEN
      remoteRef:
        key: garage/credentials
        property: GARAGE_ADMIN_TOKEN
    - secretKey: GARAGE_METRICS_TOKEN
      remoteRef:
        key: garage/credentials
        property: GARAGE_METRICS_TOKEN
    - secretKey: GARAGE_RPC_SECRET
      remoteRef:
        key: garage/credentials
        property: GARAGE_RPC_SECRET
