apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-core
spec:
  provider:
    vault:
      server: http://vault.vault-system.svc:8200
      path: secret
      version: v2
      auth:
        kubernetes:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
          mountPath: kubernetes
          role: external-secrets
