apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-smoke
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-core
    kind: ClusterSecretStore
  target:
    name: vault-smoke
    creationPolicy: Owner
  data:
    - secretKey: message
      remoteRef:
        key: bootstrap
        property: message
