apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

commonLabels:
  deploykube.certificates/purpose: ingress

resources:
  - garage-certificate.yaml
  - forgejo-certificate.yaml
  - argocd-certificate.yaml
  - keycloak-certificate.yaml
  - vault-certificate.yaml
  - kiali-certificate.yaml
  - hubble-certificate.yaml
  - grafana-certificate.yaml
