apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../smoke-tests/overlays/proxmox-talos
patches:
  - path: patch-vpa-requests-deployment-kyverno-background-controller.yaml
  - path: patch-vpa-requests-deployment-kyverno-reports-controller.yaml
  - path: patch-vpa-requests-deployment-kyverno-admission-controller.yaml
  - path: patch-vpa-requests-deployment-kyverno-admission-controller.yaml
  - path: patch-vpa-requests-deployment-kyverno-background-controller.yaml
  - path: patch-vpa-requests-deployment-kyverno-cleanup-controller.yaml
  - path: patch-vpa-requests-deployment-kyverno-reports-controller.yaml
  - path: patch-ha-tier-labels.yaml
