apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ../../base
  - httproute.yaml
  - oauth2-proxy-deployment.yaml
  - poddisruptionbudget-hubble-auth-proxy.yaml
patches:
  - path: patch-vpa-requests-deployment-hubble-auth-proxy.yaml
  - path: patch-vpa-requests-deployment-hubble-auth-proxy.yaml
  - path: patch-ha-tier-labels.yaml
