apiVersion: apps/v1
kind: Deployment
metadata:
  name: hubble-auth-proxy
  namespace: kube-system
  labels:
    darksite.cloud/ha-tier: tier-1
spec:
  template:
    metadata:
      labels:
        darksite.cloud/ha-tier: tier-1
