apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hubble-auth-proxy
  namespace: kube-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hubble-auth-proxy
