apiVersion: v1
kind: Service
metadata:
  name: keycloak-scim-bridge
  namespace: keycloak
  labels:
    app.kubernetes.io/name: keycloak-scim-bridge
spec:
  selector:
    app.kubernetes.io/name: keycloak-scim-bridge
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
