apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vap-tenant-namespace-label-contract.yaml
  - vap-tenant-namespace-identity-contract.yaml
  - vap-resource-contract-tier1.yaml
