apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - destinationrule.yaml
  - destinationrule-hubble-auth-proxy.yaml
  - oauth2-proxy-service.yaml
  - ../tests
