apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali-cabundle
  namespace: istio-system
data:
  openid-server-ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBsTCCAVagAwIBAgIRANUGU9S8FTeqz5RwRKOnx24wCgYIKoZIzj0EAwIwNjEV
    MBMGA1UEChMMRGVwbG95TGFiIENBMR0wGwYDVQQDExREZXBsb3lMYWIgQ0EgUm9v
    dCBDQTAeFw0yNTEwMjYwMTAwMDFaFw0zNTEwMjQwMTAwMDFaMDYxFTATBgNVBAoT
    DERlcGxveUxhYiBDQTEdMBsGA1UEAxMURGVwbG95TGFiIENBIFJvb3QgQ0EwWTAT
    BgcqhkjOPQIBBggqhkjOPQMBBwNCAARCZd5FlmDeAO2ZXDNOffUg4p+Sd5E8sVKu
    wOZVPSIL0XXyNSFszWdO1T92k3vdyvj+EPLyK+SEieFQ5UfyDYVjo0UwQzAOBgNV
    HQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBATAdBgNVHQ4EFgQU8N3uD1kL
    gAFReIwUp0iNZ5MeC0EwCgYIKoZIzj0EAwIDSQAwRgIhAKnrgufRSMY0iEZYo/kS
    qr1WsHhKivLDeNuV/FXJSx0RAiEAh+csYnpLkhQIY18yabQD20UN1huk6KYsSzT0
    psH1SlQ=
    -----END CERTIFICATE-----
