apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: examples-apps
  namespace: argocd
spec:
  project: platform
  destination:
    name: in-cluster
    namespace: argocd
  source:
    repoURL: https://forgejo-https.forgejo.svc.cluster.local/platform/cluster-config.git
    targetRevision: main
    path: apps/opt-in/examples-apps/overlays/dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground

