apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - pvc.yaml
  - cronjob-canary-write.yaml
  - cronjob-canary-backup.yaml
  - cronjob-canary-restore.yaml

