apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: grafana
  labels:
    darksite.cloud/ha-tier: tier-2
spec:
  template:
    metadata:
      labels:
        darksite.cloud/ha-tier: tier-2
