apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/helm
patches:
  - path: patch-resources.yaml
    target:
      kind: StatefulSet
      name: vault
  - path: patch-vpa-requests-statefulset-vault.yaml
  - path: patch-vpa-requests-statefulset-vault.yaml
  - path: patch-ha-tier-labels.yaml
