apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
  namespace: vault-system
spec:
  template:
    spec:
      containers:
        - name: vault
          resources:
            requests:
              cpu: "185m"
              memory: "1408Mi"
            limits:
              memory: "2112Mi"
