apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
  namespace: vault-system
  labels:
    darksite.cloud/ha-tier: tier-0
spec:
  template:
    metadata:
      labels:
        darksite.cloud/ha-tier: tier-0
