apiVersion: v1
kind: ServiceAccount
metadata:
  name: dns-sync
  namespace: dns-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dns-sync
  namespace: dns-system
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dns-sync
  namespace: dns-system
subjects:
  - kind: ServiceAccount
    name: dns-sync
    namespace: dns-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dns-sync
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dns-sync
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["tenancy.darksite.cloud"]
    resources: ["tenants"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["dns.darksite.cloud"]
    resources: ["dnszones"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dns-sync
subjects:
  - kind: ServiceAccount
    name: dns-sync
    namespace: dns-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dns-sync
