apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mimir-store-gateway-zone-b
  namespace: mimir
spec:
  template:
    spec:
      containers:
        - name: store-gateway
          resources:
            requests:
              cpu: "50m"
              memory: "256Mi"
            limits:
              memory: "384Mi"
