apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mimir-compactor
  namespace: mimir
spec:
  template:
    spec:
      containers:
        - name: compactor
          resources:
            requests:
              cpu: "50m"
              memory: "256Mi"
            limits:
              memory: "384Mi"
