apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: kubernetes-apiserver-no-mtls
  namespace: argocd
spec:
  host: kubernetes.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE

