apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: argocd-redis-egress
  namespace: argocd
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - redis-ha
          - redis-ha-haproxy
      - key: release
        operator: In
        values:
          - argo-cd
  policyTypes:
    - Egress
  egress:
    # Redis servers/haproxy and sidecars communicate in-namespace.
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: argocd

    # DNS
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              app.kubernetes.io/name: coredns
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP

    # Istio control plane (xDS)
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: istio-system
      ports:
        - port: 15012
          protocol: TCP
        - port: 15017
          protocol: TCP
