apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - patch: |-
      - op: replace
        path: /spec/schedule
        value: "0 * * * *"
    target:
      kind: CronJob
      name: policy-kyverno-smoke-baseline

