apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forgejo
resources:
  - httproute.yaml
  - job-https-switch.yaml
configMapGenerator:
  - name: forgejo-https-switch-script
    files:
      - https-switch.sh
generatorOptions:
  disableNameSuffixHash: true
