apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/helm
patches:
  - path: patch-statefulset-replicas.yaml
    target:
      kind: StatefulSet
      name: vault
  - path: patch-vault-configmap-raft-config-single.yaml
    target:
      kind: ConfigMap
      name: vault-config
