apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault-system
data:
  extraconfig-from-values.hcl: |-
    ui = true

    listener "tcp" {
      address = "0.0.0.0:8200"
      cluster_address = "0.0.0.0:8201"
      tls_disable = 1
    }

    storage "raft" {
      path = "/vault/data"
    }

    service_registration "kubernetes" {}

    seal "transit" {
      address = "__VAULT_SEAL_ADDR__"
      token = "__VAULT_SEAL_TOKEN__"
      disable_renewal = false
      key_name = "autounseal"
      mount_path = "transit/"
    }

    disable_mlock = true
