apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - httproute.yaml
  - configmap-argocd-https-switch-state.yaml
  - job-https-switch.yaml
configMapGenerator:
  - name: argocd-https-switch-script
    files:
      - https-switch.sh
