apiVersion: v1
kind: Namespace
metadata:
  name: forgejo
  labels:
    darksite.cloud/postgres-client: "true"
    darksite.cloud/valkey-client: "true"
    deploykube.gitops/component: forgejo
    deploykube.gitops/owner: platform
    deploykube.gitops/public-gateway: allowed
    istio-injection: enabled
    observability.grafana.com/tenant: platform
