apiVersion: v1
kind: Namespace
metadata:
  name: platform-ops
  labels:
    deploykube.gitops/component: platform-ops
    deploykube.gitops/owner: platform
    istio-injection: enabled
    observability.grafana.com/tenant: platform
