apiVersion: v1
kind: Namespace
metadata:
  name: vault-system
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    app.kubernetes.io/part-of: secrets-stack
    deploykube.gitops/component: vault
    deploykube.gitops/owner: secrets
    deploykube.gitops/public-gateway: allowed
    istio-injection: enabled
    observability.grafana.com/tenant: platform
