apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/config
patches:
  - path: patch-vault-configure-keycloak-oidc.yaml
  - path: patch-vault-configure-grafana-oidc.yaml
  - path: patch-vault-jwt-config-keycloak-oidc.yaml
  - path: patch-vault-oidc-config.yaml
  - path: patch-vault-jwt-config-schedule.yaml
  - path: patch-vault-oidc-config-schedule.yaml
  - path: patch-vault-tenant-eso-config-schedule.yaml
  - path: patch-vault-tenant-rbac-config-schedule.yaml
  - path: patch-vault-tenant-dns-rfc2136-config-schedule.yaml
