apiVersion: batch/v1
kind: Job
metadata:
  name: vault-configure
  namespace: vault-system
spec:
  template:
    spec:
      containers:
        - name: configure
          env:
            - name: GRAFANA_OIDC_HOST
              value: grafana.dev-single.internal.example.com
            - name: GRAFANA_OIDC_SCHEME
              value: https

