apiVersion: v1
kind: PersistentVolume
metadata:
  name: tier0-vault-core-proxmox-talos
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.1
    - tcp
    - soft
    - timeo=50
    - retrans=2
    - noatime
  nfs:
    server: 198.51.100.11
    path: /volume1/deploykube/backups/proxmox-talos/tier0/vault-core
  claimRef:
    namespace: vault-system
    name: vault-raft-backup

