apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-platform-apps-controller
  namespace: argocd
spec:
  source:
    path: components/platform/platform-apps-controller/overlays/proxmox-talos
