apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared-policy-kyverno
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
