apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-ops-vpa-recommendations
  namespace: argocd
spec:
  source:
    path: components/platform/ops/vpa-recommendations/overlays/proxmox-talos
