apiVersion: v1
kind: Service
metadata:
  name: platform-ntp-headless
  namespace: time-system
  labels:
    app.kubernetes.io/name: platform-ntp
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: platform-ntp
  ports:
    - name: ntp
      protocol: UDP
      port: 123
      targetPort: ntp
