apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clusterpolicy-tenant-baseline-generate.yaml
  - clusterpolicy-tenant-backup-scope-generate.yaml
  - clusterpolicy-tenant-baseline-security.yaml
  - clusterpolicy-tenant-baseline-service-types.yaml
  - clusterpolicy-tenant-deny-networkpolicy-ipblock.yaml
  - clusterpolicy-tenant-networkpolicy-guardrails.yaml
  - clusterpolicy-tenant-deny-external-secrets.yaml
  - clusterpolicy-tenant-deny-cert-manager.yaml
  - clusterpolicy-tenant-deny-cnpg.yaml
  - clusterpolicy-tenant-ingress-gateway-api-guardrails.yaml
  - clusterpolicy-tenant-pvc-storageclass-allowlist.yaml
  - clusterpolicy-tenant-pvc-deny-rwx.yaml
