apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/config
patches:
  - path: patch-vault-configure-keycloak-oidc.yaml
  - path: patch-vault-configure-grafana-oidc.yaml
  - path: patch-vault-jwt-config-keycloak-oidc.yaml
  - path: patch-vault-oidc-config.yaml
  - path: patch-openbao-smoke-prod.yaml
  - path: patch-vault-raft-backup-pvc-prod.yaml
  - path: patch-vault-raft-backup-cronjob-prod.yaml
