apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-raft-backup
  namespace: vault-system
  labels:
    darksite.cloud/backup: skip
    darksite.cloud/backup-skip-reason: backup-artifacts
spec:
  volumeName: tier0-vault-core-proxmox-talos
  storageClassName: ""
