apiVersion: batch/v1
kind: Job
metadata:
  name: vault-configure
  namespace: vault-system
spec:
  template:
    spec:
      containers:
        - name: configure
          env:
            - name: GRAFANA_OIDC_BASE_URL
              value: https://keycloak.prod.internal.example.com/realms/deploykube-admin/protocol/openid-connect
