apiVersion: batch/v1
kind: CronJob
metadata:
  name: vault-jwt-config
  namespace: vault-system
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: jwt-config
              env:
                - name: KEYCLOAK_OIDC_HOST
                  value: keycloak.prod.internal.example.com
                - name: KEYCLOAK_OIDC_SCHEME
                  value: https
