apiVersion: batch/v1
kind: Job
metadata:
  name: vault-configure
  namespace: vault-system
spec:
  template:
    spec:
      containers:
        - name: configure
          env:
            - name: KEYCLOAK_OIDC_HOST
              value: keycloak.prod.internal.example.com
            - name: KEYCLOAK_OIDC_SCHEME
              value: https
