apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vap-rbac-mutation-lock.yaml
  - vap-guardrails-self-protection.yaml
  - vap-cluster-admin-restrictions.yaml
  - vap-bindings.yaml

