apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-operator
  namespace: istio-operator
  labels:
    darksite.cloud/ha-tier: tier-2
spec:
  template:
    metadata:
      labels:
        darksite.cloud/ha-tier: tier-2
