apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: powerdns-postgres
  namespace: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "4.55"
spec:
  host: postgres-rw.dns-system.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
