apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proofs-pvc
  namespace: idlab
  labels:
    darksite.cloud/backup: skip
    darksite.cloud/backup-skip-reason: proof-of-concept
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: shared-rwo
  resources:
    requests:
      storage: 1Gi
