apiVersion: v1
kind: Secret
metadata:
  name: idlab-admin-secrets
  namespace: idlab
type: Opaque
stringData:
  ukcAdminUsername: admin
  ukcAdminPassword: Admin-UKC-123!
  mkcAdminUsername: admin
  mkcAdminPassword: Admin-MKC-123!
  btpAdminUsername: admin
  btpAdminPassword: Admin-BTP-123!
---
apiVersion: v1
kind: Secret
metadata:
  name: idlab-service-clients
  namespace: idlab
type: Opaque
stringData:
  ukcClientId: sync-controller
  ukcClientSecret: Sync-UKC-123!
  mkcClientId: mkc-scim-facade
  mkcClientSecret: Scim-MKC-123!
  btpClientId: btp-scim-facade
  btpClientSecret: Scim-BTP-123!
  scimBearerToken: SCIM-Bearer-123!
---
apiVersion: v1
kind: Secret
metadata:
  name: idlab-offline-passwords
  namespace: idlab
type: Opaque
stringData:
  aliceOfflinePassword: Alice-MKC-OFFLINE-123!
  carolOfflinePassword: Carol-MKC-OFFLINE-123!
---
apiVersion: v1
kind: Secret
metadata:
  name: idlab-postgres-app
  namespace: idlab
type: Opaque
stringData:
  username: idlab
  password: Idlab-Postgres-123!
  database: idlab
  host: idlab-postgres-rw
  port: "5432"
  uri: postgres://idlab:Idlab-Postgres-123!@idlab-postgres-rw:5432/idlab
---
apiVersion: v1
kind: Secret
metadata:
  name: idlab-postgres-superuser
  namespace: idlab
type: Opaque
stringData:
  username: postgres
  password: Idlab-Postgres-Superuser-123!
