apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-oidc-ca
  namespace: argocd
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: argocd-oidc-ca
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: ca.crt
      remoteRef:
        key: keycloak/oidc-ca
        property: ca_crt
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-oidc-ca
  namespace: forgejo
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: forgejo-oidc-ca
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: ca.crt
      remoteRef:
        key: keycloak/oidc-ca
        property: ca_crt
