apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hubble-oauth2-proxy
  namespace: kube-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: hubble-oauth2-proxy
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: clientID
      remoteRef:
        key: keycloak/hubble-client
        property: clientId
    - secretKey: clientSecret
      remoteRef:
        key: keycloak/hubble-client
        property: clientSecret
    - secretKey: cookieSecret
      remoteRef:
        key: networking/hubble/oauth2-proxy
        property: cookieSecret
    - secretKey: ca.crt
      remoteRef:
        key: keycloak/oidc-ca
        property: ca_crt

