apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-admin
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-core
  target:
    name: forgejo-admin
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: forgejo/admin
        property: username
    - secretKey: password
      remoteRef:
        key: forgejo/admin
        property: password

