apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tenant-system

resources:
  - namespace.yaml
  - dns.darksite.cloud_dnszones.yaml
  - tenancy.darksite.cloud_tenants.yaml
  - tenancy.darksite.cloud_tenantprojects.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - deployment.yaml
  - serviceaccount-tenant-forgejo-controller.yaml
  - rbac-tenant-forgejo-controller.yaml
  - externalsecret-forgejo-admin.yaml
  - deployment-tenant-forgejo-controller.yaml
