apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-state-metrics
  namespace: observability
spec:
  template:
    spec:
      containers:
        - name: kube-state-metrics
          resources:
            requests:
              cpu: "15m"
              memory: "112Mi"
            limits:
              memory: "168Mi"
