apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: kube-state-metrics-port-permissive
  namespace: observability
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
      app.kubernetes.io/instance: kube-state-metrics
  mtls:
    mode: STRICT
  portLevelMtls:
    "8080":
      mode: PERMISSIVE
