apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certificates-smoke-tests
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: platform
  destination:
    name: in-cluster
    namespace: cert-manager
  source:
    repoURL: https://forgejo-https.forgejo.svc.cluster.local/platform/cluster-config.git
    targetRevision: main
    path: components/certificates/smoke-tests/base
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - ServerSideApply=true
