apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-postgres-keycloak
  namespace: argocd
  annotations:
    # Depends on `secrets-keycloak` for the bootstrap Secret `keycloak-db`.
    argocd.argoproj.io/sync-wave: "1.4"
spec:
  project: platform
  destination:
    name: in-cluster
    namespace: keycloak
  source:
    repoURL: https://forgejo-https.forgejo.svc.cluster.local/platform/cluster-config.git
    targetRevision: main
    path: components/data/postgres/keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
