apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: networking-metallb-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: platform
  destination:
    name: in-cluster
    namespace: metallb-system
  source:
    repoURL: https://forgejo-https.forgejo.svc.cluster.local/platform/cluster-config.git
    targetRevision: main
    path: components/networking/metallb/overlays/mac-orbstack-single
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - ServerSideApply=true
