apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-ops-istio-cert-monitor
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "13"
spec:
  project: platform
  destination:
    name: in-cluster
    namespace: platform-ops
  source:
    repoURL: https://forgejo-https.forgejo.svc.cluster.local/platform/cluster-config.git
    targetRevision: main
    path: components/platform/ops/istio-cert-monitor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
