apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-observability-mimir
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2.5"
spec:
  project: platform
  destination:
    name: in-cluster
    namespace: mimir
  source:
    repoURL: https://forgejo-https.forgejo.svc.cluster.local/platform/cluster-config.git
    targetRevision: main
    path: components/platform/observability/mimir
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
