apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-ops-vertical-pod-autoscaler
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6.1"
spec:
  project: platform
  destination:
    name: in-cluster
    namespace: kube-system
  source:
    repoURL: https://forgejo-https.forgejo.svc.cluster.local/platform/cluster-config.git
    targetRevision: main
    path: components/platform/ops/vertical-pod-autoscaler
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
      - ServerSideApply=true
