apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/manifest-generate-options: "--enable-helm --helm-command ./tools/kustomize-helm-wrapper.sh"
spec:
  project: platform
  destination:
    name: in-cluster
    namespace: vault-system
  source:
    repoURL: https://forgejo-https.forgejo.svc.cluster.local/platform/cluster-config.git
    targetRevision: main
    path: components/secrets/vault/helm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: vault
      namespace: vault-system
      jsonPointers:
        - /status
      jqPathExpressions:
        - .metadata.annotations["argocd.argoproj.io/tracking-id"]
        - .spec.revisionHistoryLimit
        - .spec.template.spec.containers[].env[]?.valueFrom.fieldRef.apiVersion
        - .spec.template.spec.containers[].ports[].protocol
        - .spec.template.spec.containers[].resources
        - .spec.template.spec.containers[].terminationMessagePath
        - .spec.template.spec.containers[].terminationMessagePolicy
        - .spec.template.spec.containers[].volumeMounts[].readOnly
        - .spec.template.spec.dnsPolicy
        - .spec.template.spec.restartPolicy
        - .spec.template.spec.schedulerName
        - .spec.template.spec.serviceAccount
        - .spec.template.spec.volumes[]?.configMap.defaultMode
        - .spec.template.spec.volumes[]?.secret.defaultMode
        - .spec.volumeClaimTemplates[].metadata
        - .spec.volumeClaimTemplates[].status
        - .spec.volumeClaimTemplates[].spec.volumeMode
        - .spec.volumeClaimTemplates[].spec.storageClassName
