apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-ntp
  namespace: time-system
  labels:
    darksite.cloud/ha-tier: tier-1
spec:
  template:
    metadata:
      labels:
        darksite.cloud/ha-tier: tier-1
