apiVersion: v1
kind: Service
metadata:
  name: factorio
  namespace: factorio
  annotations:
    metallb.universe.tf/loadBalancerIPs: 198.51.100.64
spec:
  type: LoadBalancer
  ports:
    - name: game
      port: 34197
      protocol: UDP
      targetPort: 34197
  selector:
    app: factorio
