apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: step-ca-step-certificates
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: database
        labels:
          darksite.cloud/backup: restic
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: shared-rwo
