apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
resources:
  - networkpolicies.yaml
helmGlobals:
  chartHome: charts
helmCharts:
  - name: external-secrets
    version: 1.0.0
    releaseName: external-secrets
    namespace: external-secrets
    valuesFile: values.yaml
patches:
  - path: patch-vpa-requests-deployment-external-secrets.yaml
  - path: patch-vpa-requests-deployment-external-secrets-cert-controller.yaml
  - path: patch-vpa-requests-deployment-external-secrets-webhook.yaml
  - path: patch-ha-tier-labels.yaml
