apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-secrets
  namespace: external-secrets
  labels:
    darksite.cloud/ha-tier: tier-1
spec:
  template:
    metadata:
      labels:
        darksite.cloud/ha-tier: tier-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-secrets-cert-controller
  namespace: external-secrets
  labels:
    darksite.cloud/ha-tier: tier-1
spec:
  template:
    metadata:
      labels:
        darksite.cloud/ha-tier: tier-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-secrets-webhook
  namespace: external-secrets
  labels:
    darksite.cloud/ha-tier: tier-1
spec:
  template:
    metadata:
      labels:
        darksite.cloud/ha-tier: tier-1
