apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-wave: "6.1"
resources:
  - upstream
patchesStrategicMerge:
  - recommender-args-patch.yaml
  - patch-vpa-requests-deployment-vpa-recommender.yaml
patches:
  - path: patch-ha-tier-labels.yaml
