apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-recommender
  namespace: kube-system
  labels:
    darksite.cloud/ha-tier: tier-2
spec:
  template:
    metadata:
      labels:
        darksite.cloud/ha-tier: tier-2
