apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: vpa-webhook-config
webhooks:
  - name: vpa.k8s.io
    admissionReviewVersions:
      - v1
    sideEffects: None
    timeoutSeconds: 30
    failurePolicy: Ignore
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
      - operations: ["CREATE","UPDATE"]
        apiGroups: ["autoscaling.k8s.io"]
        apiVersions: ["*"]
        resources: ["verticalpodautoscalers"]
    clientConfig:
      service:
        name: vpa-webhook
        namespace: kube-system
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDVENDQWZHZ0F3SUJBZ0lVU01nRmVYQzJoTTBPWTRxYklYNEZHWjVOMldrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZERVNNQkFHQTFVRUF3d0pVM1JsY0MxU2IyOTBNQjRYRFRJMU1USXhPREUxTkRNMU5Gb1hEVE0xTVRJeApOakUxTkRNMU5Gb3dGREVTTUJBR0ExVUVBd3dKVTNSbGNDMVNiMjkwTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBc0NMZ3EwMWlXTmR5NVFyTVdxTUtlcG8zVkl1SGJwQmRISUZwZGdvRm1IK0MKdlN4ZUdmaUNoMjlMT285L2lHblN0elJwSnhvaVdrSkk2LzBGZlpVSEd4Y1Z0TVMxVk1nZDRmWDJLdmlPbGp4YwpEZnc5RTJpYWVSVmExT0dsZlA1S1hYNjRCaG15bHVFaVppdzlyWmMyZnZMZXZIL29hd1ZxajNabmRONE40OGlXCk5aMVErNVcwcFFHeGZndThzNUZqL3ZHWC85ZXRTQ3l3VG9zcGl1Um11ZGpDUTF2dE9lbHhibWZ0QnZ2VzV0SVMKNktVSWdQS2tpa0JhSmwyc0w2Ti9IWUZia0l3cGR2SVl5MGhNZmpJMDZIU0dCekNJclB5SDVKaUpZenFkM3NMVgpPTHUxdndFa0ZUV0FMYjQybWVWNzd5UlBVaUx4dWlSTWhDQWc2QVUwN3dJREFRQUJvMU13VVRBZEJnTlZIUTRFCkZnUVVkYnF4WSs0MzdqaXhhdFFMUE9vZ2hQUEltQzR3SHdZRFZSMGpCQmd3Rm9BVWRicXhZKzQzN2ppeGF0UUwKUE9vZ2hQUEltQzR3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBbHl2NgpwcFdmTEI2OEVhYi83bEE4SDFEa3JXNFFiR3NIeWk0UTVad21vNk5HbUpkNkhjc3VYR2ROL3JRK3BEY0w4V2NEClhsKzcwV1dGMkg2cnV2Mkc2UlBYNnY0RFRQMTJxR0toUVlaeno2ZTFiUUZEdmJNbFV1cnB0NFVTejZ1TFNmWEYKbVB0UFcwRGVvcXVXeC82WG14U29oMHdNdmhYb01kR0NzNHV3YW4rSjZSSDBDVFhINVBYVTJjVXh2ekptcEY1NQpOWWppMlJJWHdhSWFyYnl4VG9IN0w4dWlpK25vTkNCWmhhZ3ZUakVCaGJlV041dGpYZDJOUmRxOVRPWlVqYk1JCjVlYitVcWtSMDBVdzFsSXljWTcwQ3ZvS0ZaYlZodUxwcThsbzNRcGZRWTR4M1dhUmNjUVR3VllQQk0wOU94WVkKY1d3dUtNMlVBb1dGVXQ5cjdnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQnNUQ0NBVmFnQXdJQkFnSVJBTlVHVTlTOEZUZXF6NVJ3UktPbngyNHdDZ1lJS29aSXpqMEVBd0l3TmpFVgpNQk1HQTFVRUNoTU1SR1Z3Ykc5NVRHRmlJRU5CTVIwd0d3WURWUVFERXhSRVpYQnNiM2xNWVdJZ1EwRWdVbTl2CmRDQkRRVEFlRncweU5URXdNall3TVRBd01ERmFGdzB6TlRFd01qUXdNVEF3TURGYU1EWXhGVEFUQmdOVkJBb1QKREVSbGNHeHZlVXhoWWlCRFFURWRNQnNHQTFVRUF4TVVSR1Z3Ykc5NVRHRmlJRU5CSUZKdmIzUWdRMEV3V1RBVApCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFSQ1pkNUZsbURlQU8yWlhETk9mZlVnNHArU2Q1RThzVkt1CndPWlZQU0lMMFhYeU5TRnN6V2RPMVQ5MmszdmR5dmorRVBMeUsrU0VpZUZRNVVmeURZVmpvMFV3UXpBT0JnTlYKSFE4QkFmOEVCQU1DQVFZd0VnWURWUjBUQVFIL0JBZ3dCZ0VCL3dJQkFUQWRCZ05WSFE0RUZnUVU4TjN1RDFrTApnQUZSZUl3VXAwaU5aNU1lQzBFd0NnWUlLb1pJemowRUF3SURTUUF3UmdJaEFLbnJndWZSU01ZMGlFWllvL2tTCnFyMVdzSGhLaXZMRGVOdVYvRlhKU3gwUkFpRUFoK2NzWW5wTGtoUUlZMTh5YWJRRDIwVU4xaHVrNktZc1N6VDAKcHNIMVNsUT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=

