apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: idlab-poc
  namespace: argocd
spec:
  project: platform
  destination:
    name: in-cluster
    namespace: idlab
  source:
    repoURL: https://forgejo-https.forgejo.svc.cluster.local/platform/cluster-config.git
    targetRevision: main
    path: components/proof-of-concepts/idlab/stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
