apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - networkpolicies.yaml
  - destinationrule-kube-apiserver.yaml
  - ciliumnetworkpolicy-kube-apiserver.yaml
  - ciliumnetworkpolicy-grafana-kube-apiserver.yaml
