apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../smoke-tests

patches:
  # Override the service with the proxmox-specific pinned IP
  - path: service.yaml
  - path: patch-vpa-requests-deployment-minecraft.yaml
