apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: patch-platformapps.yaml
  - path: patch-deployment-image.yaml
  - path: patch-ha-tier-labels.yaml
